### ISSUE TITLE
编译qblk时候遇到的问题

### ISSUE THREAD

**Issue by Ideasay** [WNLO-DSAL/QBLK#1]
同学，你好。
1.我使用的内核是linux 4.16.8，是不是只能使用linux 4.16.0 啊？
2.readme文件里面说可能要修改core.c等文件。而我在编译时候遇到下面报错。
#报错
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa32_to_ppa64’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:992:10: error: ‘struct <anonymous>’ has’
   ppa64.c.q_idx = (ppa32 & ((~0U) >> 1)) >> 20;
          ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa64_to_ppa32’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1022:19: error: ‘struct <anonymous>’ ha’
   ppa32 |= ppa64.c.q_idx << 20;
                   ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_atomic_get:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1076:36: error: ‘struct ppa_addr’ has n’
   ppa.ppa = atomic64_read(&map[lba].ppa_atomic);
                                    ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_atomic_set:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1093:25: error: ‘struct ppa_addr’ has n’
   atomic64_set(&map[lba].ppa_atomic, ppa.ppa);
                         ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_atomic_get:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1111:39: error: ‘struct ppa_addr’ has n’
   oldppa.ppa = atomic64_xchg(&map[lba].ppa_atomic, ppa.ppa);
                                       ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_tomic_cmp_:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1135:43: error: ‘struct ppa_addr’ has n’
   cur_ppa.ppa = atomic64_cmpxchg(&map[lba].ppa_atomic, oldppa.ppa, newppa.ppa);
                                           ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_cacheline_to_addr’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1177:5: error: ‘struct <anonymous>’ has’
  p.c.q_idx = queueIndex;
     ^
scripts/Makefile.build:324: recipe for target '/home/femu/git/QBLK/drivers/qblkd
make[2]: *** [/home/femu/git/QBLK/drivers/qblk/qblk-core.o] Error 1
Makefile:1561: recipe for target '_module_/home/femu/git/QBLK/drivers/qblk' faid
make[1]: *** [_module_/home/femu/git/QBLK/drivers/qblk] Error 2
make[1]: Leaving directory '/home/femu/linux-version/linux-4.16.8'
Makefile:22: recipe for target 'default' failed
make: *** [default] Error 2

是不是需要说明修改什么代码额？
3.我不太懂上面的报错。能不能给俺指个方向？最后谢谢你，同学！

**Comment by HongweiQin** [comment]
Hi,

> 1.我使用的内核是linux 4.16.8，是不是只能使用linux 4.16.0 啊？

I haven't tried 4.16.8 yet. I strongly recommend you to use 4.16.0 for QBLK.

> 2.readme文件里面说可能要修改core.c等文件。而我在编译时候遇到下面报错。
> #报错
> /home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa32_to_ppa64’:
> 是不是需要说明修改什么代码额？

Can you provide your workflow of this compilation error?

> 3.我不太懂上面的报错。能不能给俺指个方向？最后谢谢你，同学！

It seems that your error message is truncated. Please provide the whole message along with your workflow so that we can figure out which part is missed.
Thanks for your attention to QBLK.

**Comment by Ideasay** [comment]
Hi, thanks for your reply and I will try linux 4.16.0~
 
 >Can you provide your workflow of this compilation error?

Does the workflow refer to this?

>femu@zheng:~/git/QBLK/drivers/qblk$ make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/home/femu/linux-version/linux-4.16.8'
  CC [M]  /home/femu/git/QBLK/drivers/qblk/qblk-core.o
In file included from /home/femu/git/QBLK/drivers/qblk/qblk-core.c:1:0:

> It seems that your error message is truncated. Please provide the whole message along with your workflow so that we can figure out which part is missed.

emmm, the whole message is as follows:

>femu@zheng:~/git/QBLK/drivers/qblk$ make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/home/femu/linux-version/linux-4.16.8'
  CC [M]  /home/femu/git/QBLK/drivers/qblk/qblk-core.o
In file included from /home/femu/git/QBLK/drivers/qblk/qblk-core.c:1:0:
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa32_to_ppa64’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:992:10: error: ‘struct <anonymous>’ has’
   ppa64.c.q_idx = (ppa32 & ((~0U) >> 1)) >> 20;
          ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa64_to_ppa32’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1022:19: error: ‘struct <anonymous>’ ha’
   ppa32 |= ppa64.c.q_idx << 20;
                   ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_atomic_get:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1076:36: error: ‘struct ppa_addr’ has n’
   ppa.ppa = atomic64_read(&map[lba].ppa_atomic);
                                    ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_atomic_set:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1093:25: error: ‘struct ppa_addr’ has n’
   atomic64_set(&map[lba].ppa_atomic, ppa.ppa);
                         ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_atomic_get:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1111:39: error: ‘struct ppa_addr’ has n’
   oldppa.ppa = atomic64_xchg(&map[lba].ppa_atomic, ppa.ppa);
                                       ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_trans_map_tomic_cmp_:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1135:43: error: ‘struct ppa_addr’ has n’
   cur_ppa.ppa = atomic64_cmpxchg(&map[lba].ppa_atomic, oldppa.ppa, newppa.ppa);
                                           ^
/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_cacheline_to_addr’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1177:5: error: ‘struct <anonymous>’ has’
  p.c.q_idx = queueIndex;
     ^
scripts/Makefile.build:324: recipe for target '/home/femu/git/QBLK/drivers/qblkd
make[2]: *** [/home/femu/git/QBLK/drivers/qblk/qblk-core.o] Error 1
Makefile:1561: recipe for target '_module_/home/femu/git/QBLK/drivers/qblk' faid
make[1]: *** [_module_/home/femu/git/QBLK/drivers/qblk] Error 2
make[1]: Leaving directory '/home/femu/linux-version/linux-4.16.8'
Makefile:22: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by HongweiQin** [comment]
Hi,
1, Did you copy the files in this repo to your kernel source? E.g., did you copy `QBLK/include/linux/lightnvm.h` to `linux/include/linux/`?

2, Look at this error message:
`/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa64_to_ppa32’:
/home/femu/git/QBLK/drivers/qblk/qblk.h:1022:19: error: ‘struct ’ ha’
ppa32 |= ppa64.c.q_idx << 20;`

Clearly, some thing is missing.
I assume it should be "struct xxx has no member xxx"? 
Nevertheless, it looks like you didn't copy enough files.

**Comment by Ideasay** [comment]
> Hi,
> 
> 1, Did you copy the files in this repo to your kernel source? E.g., did you copy `QBLK/include/linux/lightnvm.h` to `linux/include/linux/`?
> 
> 
> 
> 2, Look at this error message:
> 
> `/home/femu/git/QBLK/drivers/qblk/qblk.h: In function ‘qblk_ppa64_to_ppa32’:
> 
> /home/femu/git/QBLK/drivers/qblk/qblk.h:1022:19: error: ‘struct ’ ha’
> 
> ppa32 |= ppa64.c.q_idx << 20;`
> 
> 
> 
> Clearly, some thing is missing.
> 
> I assume it should be "struct xxx has no member xxx"? 
> 
> Nevertheless, it looks like you didn't copy enough files.

omg...
do you mean that:
if my kernel source fold is linux-4.16, I should git clone your
repo and copy the file to the folds under linux-4.16. if there dees not exit include fold, I should create one then copy the files?.finally, compile the kernel?
QWQ, thanks for reply. I will try again !!!!
